export const DATA_SOURCE = 'DATA_SOURCE';
export const DB_OPTIONS = 'DB_OPTIONS';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
export const PROFILE_REPOSITORY = ' PROFILE_REPOSITORY';
export const SPRINT_REPOSITORY = 'SPRINT_REPOSITORY';
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
export const MEMBER_REPOSITORY = 'MEMBER_REPOSITORY ';
